export const LOAD_CARDS = "LOAD_CARDS";
export const OPEN_NEW_CARD_MODAL = "OPEN_NEW_CARD_MODAL";
export const CLOSE_NEW_CARD_MODAL = "CLOSE_NEW_CARD_MODAL";
export const OPEN_CARD_MODAL = "OPEN_CARD_MODAL";
export const CLOSE_CARD_MODAL = "CLOSE_CARD_MODAL";